name: 'Build Steps'
description: 'Shared build steps for all jobs'
inputs:
  test-label:
    description: 'Test label to filter which tests to run'
    required: false
    default: 'unit'
runs:
  using: 'composite'
  steps:
    - name: Execute build
      uses: ./.github/actions/build-steps

    - name: Compile tests
      run: npm run compile-tests
      shell: bash

    - name: Run tests (Linux only)
      if: runner.os == 'Linux'
      run: xvfb-run -a npm run test:${{ inputs.test-label }}
      shell: bash

    - name: Run tests (Windows/macOS)
      if: runner.os != 'Linux'
      run: npm run test:${{ inputs.test-label }}
      shell: bash